# Generated by Django 5.1.2 on 2024-11-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('valid_number', models.BooleanField(null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('international', models.CharField(blank=True, max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('country_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prefix', models.CharField(blank=True, max_length=200, null=True)),
                ('validation_attempted', models.BooleanField(default=False)),
                ('dispatch', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('assigned', 'Assigned'), ('blocked', 'Blocked')], default='Pending', max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
